name: Deploy Podspec

on:
  push:
    tags: '*.*.**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin
        uses: actions/checkout@v2
        with:
          path: main
      - name: Extract Tag
        id: tag
        run: echo ::set-output name=name::${GITHUB_REF#refs/*/}
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FW_MWPODSPEC_DEPLOY_PAT }}
          repository: FutureWorkshops/MWPodspecs
          path: repo
      - name: Update MobileWorkflow Folder
        env:
          TAG_VERSION: ${{ steps.tag.outputs.name }}
        run: |
          if [ ! -d "./repo/MobileWorkflow" ]; then
            mkdir "./repo/MobileWorkflow"
          fi
          if [ ! -d "./repo/MobileWorkflow/${TAG_VERSION}" ]; then
            mkdir "./repo/MobileWorkflow/${TAG_VERSION}"
            cp "./main/MobileWorkflow.podspec" "./repo/MobileWorkflow/${TAG_VERSION}/MobileWorkflow.podspec"
          fi
      - name: Commit new version
        env:
          TAG_VERSION: ${{ steps.tag.outputs.name }}
        run: |
          cd repo
          git config --local user.email "c-i@futureworkshops.com"
          git config --local user.name "Continuous Integration"
          git add .
          git commit -m "MobileWorkflow [${TAG_VERSION}]"
          cd ..
      - name: Push new version
        run: |
          cd repo
          git push origin
          cd ..
